2024-08-03 17:55:51,065 Fetching raw dataset.
2024-08-03 17:55:51,879 Cleaning data.
Traceback (most recent call last):
  File "/home/lucas/Project-Build-an-ML-Pipeline-Starter/src/basic_cleaning/run.py", line 101, in <module>
    go(args)
  File "/home/lucas/Project-Build-an-ML-Pipeline-Starter/src/basic_cleaning/run.py", line 36, in go
    idx = df(df['longitude'].between(-74.25, -73.50) & df['latitude'].between(40.5, 41.2))
TypeError: 'DataFrame' object is not callable